let cacheName = 'daregiaohtmlpwa-son-v.1.0.0';
let filesToCache = [
    './',
    'index.html',
    'bootstrap/css/bootstrap.css',
    'bootstrap/css/bootstrap.css.css',
    'bootstrap/css/bootstrap.min.css',
    'bootstrap/css/bootstrap.min.css.css',
    'bootstrap/css/bootstrap-grid.css',
    'bootstrap/css/bootstrap-grid.css.css',
    'bootstrap/css/bootstrap-grid.min.css',
    'bootstrap/css/bootstrap-grid.min.css.css',
    'bootstrap/css/bootstrap-reboot.css',
    'bootstrap/css/bootstrap-reboot.css.css',
    'bootstrap/css/bootstrap-reboot.min.css',
    'bootstrap/css/bootstrap-reboot.min.css.css',
    'bootstrap/js/bootstrap.css',
    'bootstrap/js/bootstrap.min.css',
    'fonts/font-awesome/css/font-awesome.css',
    'fonts/font-awesome/css/font-awesome.min.css',
    'fonts/font-awesome/fonts/FontAwesome.otf',
    'fonts/font-awesome/fonts/fontawesome-webfont.eot',
    'fonts/font-awesome/fonts/fontawesome-webfont.svg',
    'fonts/font-awesome/fonts/fontawesome-webfont.ttf',
    'fonts/font-awesome/fonts/fontawesome-webfont.woff',
    'fonts/font-awesome/fonts/fontawesome-webfont.woff2',
    'fonts/font-awesome/less/animated.less',
    'fonts/font-awesome/less/bordered-pulled.less',
    'fonts/font-awesome/less/core.less',
    'fonts/font-awesome/less/fixed-width.less',
    'fonts/font-awesome/less/font-awesome.less',
    'fonts/font-awesome/less/icons.less',
    'fonts/font-awesome/less/larger.less',
    'fonts/font-awesome/less/list.less',
    'fonts/font-awesome/less/mixins.less',
    'fonts/font-awesome/less/path.less',
    'fonts/font-awesome/less/rotated-flipped.less',
    'fonts/font-awesome/less/screen-reader.less',
    'fonts/font-awesome/less/stacked.less',
    'fonts/font-awesome/less/variables.less',
    'fonts/font-awesome/scss/_animated.scss',
    'fonts/font-awesome/scss/_bordered-pulled.scss',
    'fonts/font-awesome/scss/_core.scss',
    'fonts/font-awesome/scss/_fixed-width.scss',
    'fonts/font-awesome/scss/_icons.scss',
    'fonts/font-awesome/scss/_larger.scss',
    'fonts/font-awesome/scss/_list.scss',
    'fonts/font-awesome/scss/_mixins.scss',
    'fonts/font-awesome/scss/_path.scss',
    'fonts/font-awesome/scss/_rotated-flipped.scss',
    'fonts/font-awesome/scss/_screen-reader.scss',
    'fonts/font-awesome/scss/_stacked.scss',
    'fonts/font-awesome/scss/_variables.scss',
    'fonts/font-awesome/scss/font-awesome.scss',
    'fonts/fontello/css/animation.css',
    'fonts/fontello/css/fontello.css',
    'fonts/fontello/css/fontello-codes.css',
    'fonts/fontello/css/fontello-embedded.css',
    'fonts/fontello/css/fontello-ie7.css',
    'fonts/fontello/css/fontello-ie7-codes.css',
    'fonts/fontello/font/fontello.eot',
    'fonts/fontello/font/fontello.svg',
    'fonts/fontello/font/fontello.ttf',
    'fonts/fontello/font/fontello.woff',
    'fonts/fontello/config.json',
    'css/skins/blue.css',
    'css/animate.css',
    'css/animations.css',
    'css/custom.css',
    'css/mixins.css',
    'css/print-invoice.css',
    'css/rtl_style.css',
    'css/rtl_typography-default.css',
    'css/rtl_typography-scheme-2.css',
    'css/style.css',
    'css/typography-default.css',
    'css/typography-scheme-2.css',
    'js/coming.soon.config.js',
    'js/custom.js',
    'js/google.map.config.js',
    'js/template.js',
    'js/scripts.js',
    'js/plugins/bootstrap-notify/bootstrap-notify.js',
    'js/plugins/bootstrap-notify/bootstrap-notify.min.js',
    'js/plugins/charts/Chart.js',
    'js/plugins/charts/Chart.min.js',
    'js/plugins/fullpage/jquery.fullpage.css',
    'js/plugins/fullpage/jquery.fullpage.extensions.min.js',
    'js/plugins/fullpage/jquery.fullpage.js',
    'js/plugins/fullpage/jquery.fullpage.min.css',
    'js/plugins/fullpage/jquery.fullpage.min.css.map',
    'js/plugins/fullpage/jquery.fullpage.min.js',
    'js/plugins/fullpage/jquery.fullpage.min.js.map',
    'js/plugins/hover/hover.css',
    'js/plugins/hover/hover-min.css',
    'js/plugins/isotope/imagesloaded.pkgd.min.js',
    'js/plugins/isotope/isotope.pkgd.js',
    'js/plugins/isotope/isotope.pkgd.min.js',
    'js/plugins/jasny-bootstrap/css/jasny-bootstrap.css',
    'js/plugins/jasny-bootstrap/css/jasny-bootstrap.css.map',
    'js/plugins/jasny-bootstrap/css/jasny-bootstrap.min.css',
    'js/plugins/jasny-bootstrap/js/jasny-bootstrap.js',
    'js/plugins/jasny-bootstrap/js/jasny-bootstrap.min.js',
    'js/plugins/magnific-popup/jquery.magnific-popup.js',
    'js/plugins/magnific-popup/jquery.magnific-popup.min.js',
    'js/plugins/magnific-popup/magnific-popup.css',
    'js/plugins/morphext/morphext.css',
    'js/plugins/morphext/morphext.js',
    'js/plugins/morphext/morphext.min.js',
    'js/plugins/owlcarousel2/assets/ajax-loader.gif',
    'js/plugins/owlcarousel2/assets/owl.carousel.css',
    'js/plugins/owlcarousel2/assets/owl.carousel.min.css',
    'js/plugins/owlcarousel2/assets/owl.theme.default.css',
    'js/plugins/owlcarousel2/assets/owl.theme.default.min.css',
    'js/plugins/owlcarousel2/assets/owl.theme.green.css',
    'js/plugins/owlcarousel2/assets/owl.theme.green.min.css',
    'js/plugins/owlcarousel2/assets/owl.video.play.png',
    'js/plugins/owlcarousel2/owl.carousel.js',
    'js/plugins/owlcarousel2/owl.carousel.min.js',
    'js/plugins/pace/pace.min.js',
    'js/plugins/slimscroll/jquery.slimscroll.js',
    'js/plugins/slimscroll/jquery.slimscroll.min.js',
    'js/plugins/waypoints/jquery.waypoints.js',
    'js/plugins/waypoints/jquery.waypoints.min.js',
    'js/plugins/waypoints/sticky.js',
    'js/plugins/waypoints/sticky.min.js',
    'js/plugins/jquery.countTo.js',
    'js/plugins/jquery.knob.min.js',
    'js/plugins/jquery.min.js',
    'js/plugins/jquery.parallax-1.1.3.js',
    'js/plugins/jquery.validate.js',
    'js/plugins/modernizr.js',
    'js/plugins/popper.min.js',
    'sass/mixins/_buttons.scss',
    'sass/mixins/_center-block.scss',
    'sass/mixins/_clearfix.scss',
    'sass/mixins/_gradients.scss',
    'sass/mixins/_hide-text.scss',
    'sass/mixins/_opacity.scss',
    'sass/mixins/_rtl.scss',
    'sass/mixins/_size.scss',
    'sass/mixins/_vendor-prefixes.scss',
    'sass/skins/blue.scss',
    'sass/_1_elements.scss',
    'sass/_2_layout.scss',
    'sass/_3_sections.scss',
    'sass/_4_pages.scss',
    'sass/_5_components.scss',
    'sass/_6_navigations.scss',
    'sass/_7_blocks-widgets.scss',
    'sass/_8_main-slideshow.scss',
    'sass/_9_owl-carousel.scss',
    'sass/_10_full-page.scss',
    'sass/_mixins.scss',
    'sass/_variables.scss',
    'sass/rtl_style.scss',
    'sass/rtl_typography-default.scss',
    'sass/rtl_typography-scheme-2.scss',
    'sass/style.scss',
    'sass/typography-default.scss',
    'sass/typography-scheme-2.scss'       
];

self.addEventListener('install', function (e) {
    console.log('[ServiceWorker] Installer');
    e.waitUntil(
        caches.open(cacheName).then(function(cache) {
            console.log('[ServiceWorker] Caching app shell');
            return cache.addAll(filesToCache);
        })
    );
});

self.addEventListener('activate', function (e) {
    console.log('[ServiceWorker] Activate');
    e.waitUntil(
        caches.keys().then(function (keyList) {
            return Promise.all(keyList.map(function(key) {
                if (key !== cacheName) {
                    console.log('[ServiceWorker] Removing old cache', key);
                    return caches.delete(key);
                }
            }));
        })
    );
});

self.addEventListener('fetch', function (e) {
    console.log('[ServiceWorker] Fetch', e.request.url);
    e.respondWith(
        caches.match(e.request).then(function(response) {
            return response || fetch(e.request);
        })
    );
});
